// <auto-generated />
namespace DbModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_weixin_list : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_weixin_list));
        
        string IMigrationMetadata.Id
        {
            get { return "201806190926331_update_weixin_list"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
